server:
  port: 2028
app:
  topic:
    sms: smsTopic
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bwongo_sms_db}
    username: ${DB_USERNAME:aaron}
    password: ${DB_PASSWORD:aaron}
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      group-id: sms-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
       spring.json.trusted.packages: "*"
#  ert:
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#           deserializer:
#             key:
#               delegate:
#                 class: org.apache.kafka.common.serialization.StringDeserializer
#             value:
#               delegate:
#                 class: org.springframework.kafka.support.serializer.JsonDeserializer
#           json:
#             value:
#               default:
#                 type: com.bwongo.notification_service.base.model.dto.NotificationDto

#             trusted:
#               packages: com.bwongo.notification_service.base.model.dto