name: CI-CD Pipeline

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        context: ./core
        run: ./gradlew clean build

      - name: Build Core Docker image
        context: ./core
        run: docker build -t bwongo-sms-core-app:latest

      - name: Run Docker Compose integration tests
        run: docker-compose up --build --exit-code-from app

      - name: Push Docker Image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin

      - name: Tag Docker image
        run: docker tag bwongo-sms-core-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bwongo-sms-core-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd services/bwongo_sms
            docker-compose down
            docker-compose pull
            docker-compose up -d